
sudo: required

language: bash

services: 
- docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=shakahl/ansible-runner-docker
  - DOCKER_IMAGE=shakahl/ansible-runner-docker

script:
 - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
 - docker build -t $REPO:$TAG -f Dockerfile .

script:
  - docker build -t ${DOCKER_IMAGE} .
  - docker push $IMAGE_NAME:$CI_BUILD_REF

after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
 - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
   docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
   docker push $REPO:$TRAVIS_BUILD_NUMBER;
   fi 
 - docker push $REPO:$TAG

