sudo: required

language: bash
services: docker

env:
 - DOCKER_IMAGE=shakahl/ansible-runner

script:
  - docker build -t ${DOCKER_IMAGE} .

# after_script:
#   - docker images
#   - docker run -t ${DOCKER_IMAGE}
#   - docker ps -a
